#!/bin/bash

#PBS -N citeseqhash
#PBS -q batch
#PBS -l nodes=1:ppn=8
#PBS -l mem=160GB
#PBS -l walltime=60:00:00
#PBS -A kidn1
#PBS -m abe
#PBS -M sean.wilson@mcri.edu.au

cd $PBS_O_WORKDIR
hashdir = /group/kidn1/Group-Little_MCRI/Data/SingleCellRNASeq/FactorialScreen2019/data/Hashing
module load R python

source /group/kidn1/hpc/cite-seq-count/bin/activate

CITE-seq-Count \
-R1 SW_CPT1_hto/all_R1.fastq.gz \
-R2 SW_CPT1_hto/all_R2.fastq.gz \
-t /group/kidn1/Group-Little_MCRI/Data/SingleCellRNASeq/FactorialScreen2019/data/Hashing/tags.csv \
-cbf 1 \
-cbl 16 \
-umif 17 \
-umil 26 \
-cells 20000 \
-o SW_CPT1_HTO
